name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Gracias por informar de un error o de informar de una caracteristica necesaria'
        pr-message: 'Gracias por realizar una pull-request, seras avisado cuando sea aceptada'
